--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Faizx511x/EndSkyWars-Fix
build-by-default: true
branches:
- master
projects:
  EndSkyWars-Fix:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
    lint: false
...
