---
# MySQL
SkyWars-SQL:
  Host: 127.0.0.1
  User: root
  Password: ""
  Database: your_schema
  Port: 3306
  
# Settings
lastDay: 0
lastWeek: 0
lastMonth: 0
level-required-for-rating: 5
builder-mode: false
name-server: "SkyWars > Join now!"
